#! /bin/sh
#  /etc/init.d/superpipes

### BEGIN INIT INFO
# Provides:          superpipes
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the service
# Description:       This file is used to start the daemon
#                    and should be placed in /etc/init.d
### END INIT INFO

# Copyright (C) 2013 Fabien Vauchelles (fabien_AT_vauchelles_DOT_com).
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 3, 29 June 2007, of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301  USA

NAME="superpipes"
DESC="$NAME service"

# The path to Jsvc
EXEC=`which jsvc`

# The path to the folder containing the jar
FILE_PATH="/usr/local/$NAME"

# Our classpath including our jar file and the Apache Commons Daemon library
CLASS_PATH="$FILE_PATH/lib/*.jar:$FILE_PATH/$NAME.jar"

# The fully qualified name of the class to execute
CLASS="com.vaushell.superpipes.DaemonApp"

# Any command line arguments to be passed to the our Java Daemon implementations init() method
ARGS="/usr/local/$NAME/conf/configuration.xml /usr/local/$NAME/datas"

#The user to run the daemon as
USER="superpipes"

# The file that will contain our process identification number (pid) for other scripts/programs that need to access it.
PID="/usr/local/$NAME/$NAME.pid"

# System.out writes to this file...
LOG_OUT="/usr/local/$NAME/log/info"

# System.err writes to this file...
LOG_ERR="/usr/local/$NAME/log/error"

jsvc_exec()
{
    cd "$FILE_PATH"
    $EXEC -cp "$CLASS_PATH" -user "$USER" -outfile "$LOG_OUT" -errfile "$LOG_ERR" -pidfile "$PID" $1 "$CLASS" $ARGS
}

case "$1" in
    start)
        echo "Starting the $DESC..."

        # Start the service
        jsvc_exec

        echo "The $DESC has started."
    ;;
    stop)
        echo "Stopping the $DESC..."

        # Stop the service
        jsvc_exec "-stop"

        echo "The $DESC has stopped."
    ;;
    restart)
        if [ -f "$PID" ]; then

            echo "Restarting the $DESC..."

            # Stop the service
            jsvc_exec "-stop"

            # Start the service
            jsvc_exec

            echo "The $DESC has restarted."
        else
            echo "Daemon not running, no action taken"
            exit 1
        fi
            ;;
    *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
    exit 3
    ;;
esac
